name: Build libxml2 with MSYS2
on: [push, pull_request]
jobs:
  build-libxml2:
    runs-on: windows-latest
    #env:
    #  # This isn't checked by default in MSYS2:
    #  CPPFLAGS: -I/usr/include
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          release: false
      - name: git clone
        shell: bash
        run: |
          git clone https://gitlab.gnome.org/GNOME/libxml2.git
          cd libxml2
          git checkout v2.9.10
      - name: autogen.sh
        working-directory: libxml2
        run: |
          ./autogen.sh \
            --without-c14n \
            --without-catalog \
            --without-debug \
            --without-docbook \
            --without-fexceptions \
            --without-ftp \
            --without-history \
            --with-html \
            --without-http \
            --without-iconv \
            --without-icu \
            --without-iso8859x \
            --without-legacy \
            --with-minimum \
            --without-output \
            --without-pattern \
            --without-push \
            --without-python \
            --without-reader \
            --without-readline \
            --without-regexps \
            --without-sax1 \
            --with-schemas \
            --without-schematron \
            --without-threads \
            --with-tree \
            --without-valid \
            --without-writer \
            --without-xinclude \
            --with-xpath \
            --without-xptr \
            --without-modules \
            --without-zlib \
            --without-lzma \
            --
      - name: make
        working-directory: libxml2
        run: |
          make
      - name: make install
        working-directory: libxml2
        run: |
          make install
      - name: check results
        run: |
          ls -lh /mingw64/include/libxml2/libxml
          ls -lh /mingw64/bin/libxml*
          ls -lh /mingw64/lib/libxml*
